USE ROLE DEEPSEEK_ROLE;
USE DATABASE DEEPSEEK_DB;
USE WAREHOUSE DEEPSEEK_WAREHOUSE;

USE SCHEMA DATA_SCHEMA;
SHOW IMAGE REPOSITORIES;
SHOW STAGES;

SHOW COMPUTE POOLS; --or DESCRIBE COMPUTE POOL DEEPSEEK_GPU_COMPUTE_POOL;
ALTER COMPUTE POOL DEEPSEEK_GPU_COMPUTE_POOL RESUME;

CREATE STAGE IF NOT EXISTS ollama ENCRYPTION = (TYPE='SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS specs ENCRYPTION = (TYPE='SNOWFLAKE_SSE');



DROP SERVICE IF EXISTS DEEPSEEK_DB.DATA_SCHEMA.DEEPSEEK;
create service DEEPSEEK_DB.DATA_SCHEMA.DEEPSEEK
in compute pool DEEPSEEK_GPU_COMPUTE_POOL
from @specs
spec='deepseek-in-snowflake-service_one-gpu.yml'
EXTERNAL_ACCESS_INTEGRATIONS = (DEEPSEEK_ACCESS_INTEGRATION)
;


show services in schema DEEPSEEK_DB.DATA_SCHEMA;
DESCRIBE SERVICE DEEPSEEK_DB.DATA_SCHEMA.DEEPSEEK;

SHOW ENDPOINTS IN SERVICE DEEPSEEK_DB.DATA_SCHEMA.DEEPSEEK;

ALTER SERVICE DEEPSEEK_DB.DATA_SCHEMA.DEEPSEEK SUSPEND;
ALTER SERVICE DEEPSEEK_DB.DATA_SCHEMA.DEEPSEEK RESUME;

CALL SYSTEM$GET_SERVICE_STATUS('DEEPSEEK_DB.DATA_SCHEMA.DEEPSEEK');


SELECT SYSTEM$GET_SERVICE_LOGS('DEEPSEEK_DB.DATA_SCHEMA.DEEPSEEK', '0', 'ollama', 50);
