USE ROLE ACCOUNTADMIN;
CREATE ROLE DEEPSEEK_ROLE;
CREATE DATABASE IF NOT EXISTS DEEPSEEK_DB;
GRANT OWNERSHIP ON DATABASE DEEPSEEK_DB
  TO ROLE DEEPSEEK_ROLE COPY CURRENT GRANTS;
CREATE OR REPLACE WAREHOUSE DEEPSEEK_WAREHOUSE WITH
  WAREHOUSE_SIZE='X-SMALL';
GRANT USAGE ON WAREHOUSE DEEPSEEK_WAREHOUSE
  TO ROLE DEEPSEEK_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT
  TO ROLE DEEPSEEK_ROLE;

// create compute pool
CREATE COMPUTE POOL DEEPSEEK_GPU_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 3
  INSTANCE_FAMILY = GPU_NV_S;
GRANT ALL PRIVILEGES ON COMPUTE POOL DEEPSEEK_GPU_COMPUTE_POOL TO ROLE DEEPSEEK_ROLE;

// create a user with public key (you can also use login and password)
CREATE USER DEEPSEEK_USER
    DEFAULT_ROLE = DEEPSEEK_ROLE
    RSA_PUBLIC_KEY = 'YOUR PUBLIC KEY'
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE DEEPSEEK_ROLE TO USER DEEPSEEK_USER;
GRANT ROLE DEEPSEEK_ROLE TO ROLE SYSADMIN;


////////////////////////////////////////////////////
USE ROLE DEEPSEEK_ROLE;
USE DATABASE DEEPSEEK_DB;
USE WAREHOUSE DEEPSEEK_WAREHOUSE;

CREATE SCHEMA IF NOT EXISTS DATA_SCHEMA;
USE SCHEMA DATA_SCHEMA;
CREATE IMAGE REPOSITORY IF NOT EXISTS DEEPSEEK_REPOSITORY;
