USE ROLE ACCOUNTADMIN;

// Let us setup container environment
CREATE OR REPLACE NETWORK RULE DEEPSEEK_NETWORK_RULE
MODE = EGRESS
TYPE = HOST_PORT
VALUE_LIST = ('0.0.0.0:443', '0.0.0.0:80');
-- allow access to the whole internet on port 443 and 80
GRANT OWNERSHIP ON NETWORK RULE DEEPSEEK_NETWORK_RULE
TO ROLE DEEPSEEK_ROLE REVOKE CURRENT GRANTS;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION DEEPSEEK_ACCESS_INTEGRATION
ALLOWED_NETWORK_RULES = (DEEPSEEK_NETWORK_RULE)
ENABLED = TRUE;
GRANT OWNERSHIP ON INTEGRATION DEEPSEEK_ACCESS_INTEGRATION
TO ROLE DEEPSEEK_ROLE REVOKE CURRENT GRANTS;
